---
application:
  name: "nodeyoutubedownloader"
  project: "YTD"
  organization: "QoveryCommunity"
  storage:
  - name: "adsasd"
    size: "500"
    type: "hdd"
    mount_point: "/mnt/adsasd"
routers:
- name: "main-nodeyoutubedownloader"
  routes:
  - application_name: "nodeyoutubedownloader"
    paths:
    - "/*"
